typography_spectrum: 0.16121930722147226
color:
  brandStrength: 0.9958747834898531
  lightness: 0.603547005681321
  saturation: 0.21092976862564683
  rhythmicContrast: 0.09406212088651955
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
github: true
layout_spectrum: 0.4052879011724144
author:
  name: Heidi Carine Brimi
  email: travel@tempusfugit.no
  url: tempusfugittravel.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/da57c36c-53d2-4b0f-89e3-b6290d0b6b03.png
name: Tempus Fugit Travel
navigation:
  - name: Terms and conditions
    id: 2e92e1bb-46c3-47e1-8f39-b6cabf59cd9e
    type: content
  - name: Contact
    id: 7f633374-c29d-4b76-b1fc-bdc0a58c07b0
    type: content
title: Tempus Fugit
description: Nature and heritage travels
purpose:
  - type: contact
    url: 'mailto:travel@tempusfugit.no'
    label: Contact us
